<a href="https://colab.research.google.com/github/LIvanoff/mirea-pytorch/blob/main/task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание 1

In [48]:
from torch import nn # модуль с базовыми слоями
import torch.nn.functional as F # модуль с базовыми функциями
from torch import optim

class Neuron(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = torch.nn.Linear(2, 3)
    self.activ1 = torch.nn.Sigmoid()
    self.fc2 = torch.nn.Linear(3, 3)
    self.activ2 = torch.nn.Sigmoid()
    self.fc3 = torch.nn.Linear(3, 1)

  def forward(self, x):
    x = self.fc1(x)
    x = self.activ1(x)
    x = self.fc2(x)
    x = self.activ2(x)
    x = self.fc3(x)
    return x
    # x = torch.heaviside(self.fc1(x), torch.tensor([0.0]))
    # x = torch.heaviside(self.fc2(x), torch.tensor([0.0]))
    # return torch.heaviside(self.fc3(x), torch.tensor([0.0]))
  
def fail(pred, target):
  squares = (pred - target) ** 2
  return squares.mean()
  
model = Neuron()
model.train()
x_train = torch.Tensor([[0.0,0.0], [1.0,0.0], [0.0,1.0], [1.0,1.0]])
y = torch.Tensor([[0], [1],[1], [0]])
# y = torch.Tensor([0,1,1,0])
#y = torch.Tensor(y).type(torch.LongTensor)
optimizer = torch.optim.Adam(model.parameters(), 
                             lr=1.0e-3)
#loss = nn.NLLLoss()
#loss = torch.nn.CrossEntropyLoss()
# print(model.fc.weight)
# model.forward(x)
# print(model.fc.weight)

# print(model.fc1.weight)
# OUT = model.forward(x_train)
# print(OUT)

for epoch in range(1000):
  for i in range(0, len(x_train)):
    OUT = model.forward(x_train)
    print(OUT)
    print(y)
    loss_m = fail(OUT, y)
    print(loss_m)
    loss_m.backward()
    optimizer.step()
  if epoch % 100 == 0:
        test_preds = model.forward(x_train)
        test_preds = test_preds.argmax(dim=1)
        print((test_preds == y).float().mean())

Выходные данные были обрезаны до нескольких последних строк (5000).
        [1.],
        [1.],
        [0.]])
tensor(0.3197, grad_fn=<MeanBackward0>)
tensor([[0.7634],
        [0.7637],
        [0.7638],
        [0.7638]], grad_fn=<AddmmBackward0>)
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(0.3194, grad_fn=<MeanBackward0>)
tensor([[0.7629],
        [0.7632],
        [0.7633],
        [0.7633]], grad_fn=<AddmmBackward0>)
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(0.3192, grad_fn=<MeanBackward0>)
tensor([[0.7624],
        [0.7628],
        [0.7628],
        [0.7628]], grad_fn=<AddmmBackward0>)
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(0.3189, grad_fn=<MeanBackward0>)
tensor([[0.7619],
        [0.7623],
        [0.7623],
        [0.7624]], grad_fn=<AddmmBackward0>)
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(0.3187, grad_fn=<MeanBackward0>)
tensor([[0.7615],
        [0.7618],
        [0.7618],
        [0.

# Задание 3

In [17]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F
from torch import optim

class Neuron_test(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = torch.nn.Linear(1, 1)

  def forward(self, x):
    return torch.heaviside(self.fc1(x), torch.tensor([0.0]))


model = Neuron_test().to(device)
model.to(device)
x_train = torch.cuda.FloatTensor([10000000]).to(device)
model.forward(x_train).to(device)